title: Subir Codes
description: Python + DSA Learning Hub

theme: just-the-docs

url: "https://subircodz.github.io"

nav_enabled: true

plugins:
  - jekyll-remote-theme

remote_theme: just-the-docs/just-the-docs
