title: Subir Codes
description: Python + DSA Learning Hub

theme: just-the-docs

url: "https://subircodez.github.io"

aux_links:
  "GitHub Profile":
    - "https://github.com/subircodez"

nav_enabled: true
